name: cloudflare

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: actions/setup-node@v3
      - run: yarn --frozen-lockfile
      - name: build
      - run: yarn build
      - run: wrangler whoami
        env: 
          CLOUDFLARE_ACCOUT_ID: ${{ secrets.CLOUDFLARE_ACCOUT_ID }}
